POST http://localhost:4000/app/signup
Content-Type : application/json

{
    "firstName": "Saumya",
    "lastName" : "Test Backend",
    "emailID": "saumya@aetherautomation.cpm",
    "password" : "test1"
}
