POST http://localhost:4000/app/signup
Content-Type : application/json

{
    "firstName": "Saumya",
    "lastName" : "Test Backend",
    "emailID": "saumya3@aetherautomation.cpm",
    "password" : "test1",
    "password2" : "test2"
}
